const initialTimeText = '20 : 00'
const initialTime = 20
const secondsPerMin = 60
const timeUplimit = 60
const timeLowlimit = 0
const ksStart = 0
const ksPause = 1
const ksContinue = 2
const xPos = 0
const yPos = 1
const changeTimePoint = 5
const changeImagePoint = 5
const GOLD = 'gold'
const TREE = 'tree'
const WATER = 'water'
const FIRE = 'fire'
const SOIL = 'soil'
